routes/web.php
<?php

use App\Http\Controllers\ApiConsumerController;
use App\Http\Controllers\GedungController;
use App\Http\Controllers\KategoriRuanganController;
use App\Http\Controllers\FasilitasController;
use App\Http\Controllers\RuanganController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// =========== Route For Landing-page ===========
Route::view('/', 'landingpage.home');
Route::view('/home', 'landingpage.home');
Route::view('/about', 'landingpage.about');
Route::view('/services', 'landingpage.services');
Route::view('/blog', 'landingpage.blog');
Route::view('/contact', 'landingpage.contact');
Route::view('/list', 'landingpage.list');
Route::view('/aula-atas', 'landingpage.aula-atas');
Route::view('/aula-bawah', 'landingpage.aula-bawah');
Route::view('/lapangan', 'landingpage.lapangan');
Route::view('/tepas', 'landingpage.tepas');

// =========== Route For Admin ===========
Route::view('/admin', 'admin.home');
// Route::view('/peminjaman', 'admin.peminjaman');
Route::view('/admin/pages/basictable', 'admin.pages.basictable');
Route::view('/admin/pages/basicelement', 'admin.pages.basicelement');
Route::view('/admin/pages/chart', 'admin.pages.chart');
Route::view('/admin/pages/icons', 'admin.pages.icons');

// =========== Route For Bisnis Proses ===========
// Route::resource('/gedung', GedungController::class)->middleware('auth');
// Route::resource('/users', UserController::class)->middleware('auth');
// Route::resource('/fasilitas', FasilitasController::class)->middleware('auth');
// Route::resource('/ruangan', RuanganController::class)->middleware('auth');
// // Route::get('/ruangan-delete/{id}', 'RuanganController@destroy')->name('ruangans.destory');
// // Route::get('/ruangan-delete/{id}', [RuanganController::class, 'destory'] )->name('destory');
// Route::get('/ruangan-delete/{id}', 'App\Http\Controllers\RuanganController@destroy')->middleware('auth');
// Route::resource('/kategori-ruangan', KategoriRuanganController::class);
// Route::get('/gedung-list', [GedungController::class, 'gedungList']);


// // =========== Route For Export PDF ===========
// Route::get('/generate-pdf', [RuanganController::class, 'generatePDF'])->middleware('auth');
// Route::get('/ruangan-pdf', [RuanganController::class, 'ruanganPDF'])->middleware('auth');


// Route Group for every auth
Route::group(['middleware' => ['access']], function (){
Route::resource('/gedung', GedungController::class);
Route::resource('/users', UserController::class);
Route::resource('/fasilitas', FasilitasController::class);
Route::resource('/ruangan', RuanganController::class);
// Route::get('/ruangan-delete/{id}', 'RuanganController@destroy')->name('ruangans.destory');
// Route::get('/ruangan-delete/{id}', [RuanganController::class, 'destory'] )->name('destory');
Route::get('/ruangan-delete/{id}', 'App\Http\Controllers\RuanganController@destroy');
Route::resource('/kategori-ruangan', KategoriRuanganController::class);
Route::get('/gedung-list', [GedungController::class, 'gedungList']);

// =========== Route For Export PDF ===========
Route::get('/generate-pdf', [RuanganController::class, 'generatePDF']);
Route::get('/ruangan-pdf', [RuanganController::class, 'ruanganPDF']);

// api get for ruangan
// Route::get('api/{service}', [ApiConsumerController::class,'list']);
// Route::get('api/{service}/{id}', [ApiConsumerController::class,'detail']);

});
Route::get('/peminjaman', function() {
    return view('admin.peminjaman');
});



// Route cara 2
// Route::middleware(['admin', 'staff'])->group(function () {
//     Route::resource('/gedung', GedungController::class);
//     Route::resource('/users', UserController::class);
//     Route::resource('/fasilitas', FasilitasController::class);
//     Route::resource('/ruangan', RuanganController::class);
//     // Route::get('/ruangan-delete/{id}', 'RuanganController@destroy')->name('ruangans.destory');
//     // Route::get('/ruangan-delete/{id}', [RuanganController::class, 'destory'] )->name('destory');
//     Route::get('/ruangan-delete/{id}', 'App\Http\Controllers\RuanganController@destroy');
//     Route::resource('/kategori-ruangan', KategoriRuanganController::class);
//     Route::get('/gedung-list', [GedungController::class, 'gedungList']);


//     // =========== Route For Export PDF ===========
//     Route::get('/generate-pdf', [RuanganController::class, 'generatePDF']);
//     Route::get('/ruangan-pdf', [RuanganController::class, 'ruanganPDF']);
//     // Route::view('/peminjaman', 'admin.peminjaman');

// });
// for authentication user
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::view('/after-register', 'landingpage.after_register');
Route::view('/access-denied', 'access');

app/Models/Ruangan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Ruangan extends Model
{
    use HasFactory;
    protected $table = 'ruangan';
    protected $guarded = ['id'];

    // database relationn many to one gedung
    public function gedung()
    {
        return $this->belongsTo(Gedung::class);
    }
    // database relation many to one kategori ruangan
    public function kategoriRuangan()
    {
        return $this->belongsTo(KategoriRuangan::class);
    }
}

app/Http/Controllers/RuanganController.php
<?php

namespace App\Http\Controllers;

use App\Models\Ruangan;
use App\Models\Gedung;
use App\Models\KategoriRuangan;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use PDF;

class RuanganController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // Tampil Data from Database
        $ruangan = Ruangan::latest()->paginate(5);

        return view('ruangan.index',compact('ruangan'))
            ->with('i', (request()->input('page', 1) - 1) * 5);

    }

    public function generatePDF()
    {
        $data = [
            'title' => 'Test use PDF extention',
            'date' => date('m/d/Y')
        ];

        $pdf = PDF::loadView('ruangan/myPDF', $data);

        return $pdf->download('hasil_exporPDF.pdf');
    }

    function ruanganPDF(){
        $data = Ruangan::all();
        // dd($data);
        $pdf = PDF::loadView('ruangan/ruanganPDF', ['data'=>$data]);

        return $pdf->download(date('m/d/y').'_dataruangan.pdf');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // ambil seluruh data dari kategori-ruangan
        $kategori_ruangan = KategoriRuangan::all();
        // ambil seluruh data dari Gedung
        $gedung = Gedung::all();
        // tambah input ke form database
        return view('ruangan.create', compact('kategori_ruangan','gedung'));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // Proses input data ruangan with foto
        $request->validate([
            'nama' => 'required',
            'kategori_ruangan_id' => 'required',
            'gedung_id' => 'required',
            'kapasitas' => 'required|numeric',
            'lantai' => 'required|numeric',
            'foto1' => 'image|mimes:jpeg,png,jpg,gif,svg|max:3068',
        ]);

        $input = $request->all();

        // logic for proses foto
        if ($image = $request->file('foto1')) {
            $destinationPath = 'img/ruangan';
            $profileImage = date('YmdHis') . "." . $image->getClientOriginalExtension();
            $image->move($destinationPath, $profileImage);
            $input['foto1'] = "$profileImage";
        }

        // input create gedung function
        // Ruangan::create($input);

        // kembali ke page
        // return redirect()->route('ruangan.index')
                        // ->with('success','Gedung created successfully.');

        try {
            Ruangan::create($input);

            return redirect()->route('ruangan.index')
                ->with('success', 'Ruangan Created successfully!');
        } catch (\Exception $e){
            return redirect()->back()
                ->with('error', 'Error during the creation!');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Ruangan  $ruangan
     * @return \Illuminate\Http\Response
     */
    public function show(Ruangan $ruangan)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Ruangan  $ruangan
     * @return \Illuminate\Http\Response
     */
    public function edit(Ruangan $ruangan)
    {
        // ambil seluruh data dari kategori-ruangan
        $kategori_ruangan = KategoriRuangan::all();
        // ambil seluruh data dari Gedung
        $gedung = Gedung::all();

        return view('ruangan.edit', compact('ruangan','kategori_ruangan','gedung'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Ruangan  $ruangan
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Ruangan $ruangan)
    {
//--------proses update data lama & upload file foto baru--------
        $image = $request->file('foto1');
        if(!empty($image)) //kondisi akan upload foto baru
        {
            if(!empty($ruangan->foto1)){ //kondisi ada nama file foto di tabel
                //hapus foto lama
                unlink('img/ruangan/'.$ruangan->foto1);
            }
            //proses upload foto baru
            $destinationPath = 'img/ruangan/';
            $profileImage = date('YmdHis') . "." . $image->getClientOriginalExtension();
            //print_r($profileImage); die();
            $image->move($destinationPath, $profileImage);
            $input['foto1'] = "$profileImage";
        }
        else //kondisi user hanya update data saja, bukan ganti foto
        {
            $input['foto1'] = $ruangan->foto1; //nama file foto masih yg lama
        }

        // $ruangan->update($input);

        // return redirect()->route('ruangan.index')
                        // ->with('success','Ruangan updated successfully.');
        try {
            $ruangan->update($input);

            return redirect()->route('ruangan.index')
                ->with('success', 'Edit Ruangan successfully!');
        } catch (\Exception $e){
            return redirect()->back()
                ->with('error', 'Error during the creation!');
        }

        // // Proses input data ruangan with foto
        // $request->validate([
        //     'nama' => 'required',
        //     'kategori_ruangan_id' => 'required',
        //     'gedung_id' => 'required',
        //     'kapasitas' => 'required|numeric',
        //     'lantai' => 'required|numeric',
        //     'foto1' => 'image|mimes:jpeg,png,jpg,gif,svg|max:3068',
        // ]);
        // $image = $request->file('foto1');
        // if(!empty($image)) //kondisi akan upload foto baru
        // {
        //     if(!empty($ruangan->foto1)){ //kondisi ada nama file foto di tabel
        //         //hapus foto lama
        //         unlink('img/ruangan/'.$ruangan->foto1);
        //     }
        //     //proses upload foto baru
        //     $destinationPath = 'img/ruangan/';
        //     $profileImage = date('YmdHis') . "." . $image->getClientOriginalExtension();
        //     //print_r($profileImage); die();
        //     $image->move($destinationPath, $profileImage);
        //     $input['foto1'] = "$profileImage";
        // }
        // else //kondisi user hanya update data saja, bukan ganti foto
        // {
        //     $input['foto1'] = $ruangan->foto1; //nama file foto masih yg lama
        // }

        // $ruangan->update($input);

        // return redirect()->route('ruangan.index')
        //                 ->with('success','Ruangan updated successfully.')


        // $input = $request->all();

        // // logic for proses foto
        // if ($image = $request->file('foto1')) {
        //     $destinationPath = 'img/ruangan';
        //     $profileImage = date('YmdHis') . "." . $image->getClientOriginalExtension();
        //     $image->move($destinationPath, $profileImage);
        //     $input['foto1'] = "$profileImage";
        // }

        // // input create gedung function
        // // $ruangan = Ruangan::where('id', $ruangan->id)->update($input);
        // // Ruangan::where('id', $ruangan->id)->update($request->all());
        // $ruangan->update($request->all());


        // // kembali ke page
        // return redirect()->route('ruangan.index')
        //                 ->with('success','Gedung created successfully.');
        }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Ruangan  $ruangan
     * @return \Illuminate\Http\Response
     */
    public function destroy(Ruangan $ruangan, $id)
    {
       //--------hapus dulu fisik file foto--------
       $ruangan = Ruangan::find($id);
       if(!empty($ruangan->foto1)) unlink('img/ruangan/'.$ruangan->foto1);
        // dd($ruangan = Ruangan::find($id));

        // Delete Data Mahasiswa
        // $ruangan->delete();
        $ruangan = Ruangan::where('id', $id)->delete();

        // return redirect()->route('ruangan.index')
        //                 ->with('success','deleted Data berhasil');

        return back()->with('success','Data deleted successfully');
    }
}

resources/views/ruangan/create.blade.php
@extends('admin.index')

@section('content')
    <div class="content-wrapper">
    <div class="row">
        <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
              <div class="card-body">
                <h4 class="card-title">Form input Ruangan</h4>
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <strong>Whoops!</strong> There were some problems with your input.<br><br>
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <form action="{{ route('ruangan.store') }}" method="POST" class="forms-sample" enctype="multipart/form-data">
                    @csrf
                  <div class="form-group row">
                    <label for="exampleInputUsername2" class="col-sm-3 col-form-label">Nama Ruangan</label>
                    <div class="col-sm-9">
                      <input type="text" name="nama" class="form-control" id="exampleInputUsername2" placeholder="Nama Ruangan">
                    </div>
                  </div>
                  <div class="form-group row">
                    <label for="exampleSelectGender"  class="col-sm-3 col-form-label">Kategori Ruangan</label>
                    <div class="col-sm-9">
                        <select class="form-control" id="exampleSelectGender" name="kategori_ruangan_id">
                            <option>-- Pilih Kategori Ruangan --</option>
                            @foreach ($kategori_ruangan as $kat)
                            <option value="{{ $kat->id }}">{{ $kat->nama }}</option>
                            @endforeach
                        </select>
                    </div>
                    </div>
                    <div class="form-group row">
                        <label for="exampleSelectGender"  class="col-sm-3 col-form-label">Gedung</label>
                        <div class="col-sm-9">
                            <select class="form-control" id="exampleSelectGender" name="gedung_id">
                                <option>-- Pilih Kategori Gedung --</option>
                                @foreach ($gedung as $gd)
                                <option value="{{ $gd->id }}">{{ $gd->nama }}</option>
                                @endforeach
                            </select>
                        </div>
                        </div>
                  <div class="form-group row">
                    <label for="exampleInputMobile" class="col-sm-3 col-form-label">Lantai</label>
                    <div class="col-sm-9">
                        <input type="text" name="lantai" class="form-control" placeholder="Lantai">
                    </div>
                  </div>
                  <div class="form-group row">
                    <label for="exampleInputMobile" class="col-sm-3 col-form-label">Kapasitas</label>
                    <div class="col-sm-9">
                        <input type="text" name="kapasitas" class="form-control" placeholder="Kapasitas">
                    </div>
                  </div>
                  <div class="form-group row">
                    <label for="exampleInputMobile" class="col-sm-3 col-form-label">Foto 1</label>
                    <div class="col-sm-9">
                        <input type="file" name="foto1" class="form-control" placeholder="Foto 1">
                    </div>
                  </div>
                  <div class="form-check form-check-flat form-check-primary">
                  </div>
                  <button type="submit" name="proses" class="btn btn-primary mr-2">Submit</button>
                  <a href="{{ url('ruangan')}}" class="btn btn-warning text-white">Batal</a>
                </form>
              </div>
            </div>
          </div>
    </div>
    </div>
@endsection

resources/views/ruangan/edit.blade.php
@extends('admin.index')

@section('content')
    <div class="content-wrapper">
    <div class="row">
        <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
              <div class="card-body">
                <h4 class="card-title">Form Edit Ruangan</h4>
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <strong>Whoops!</strong> There were some problems with your input.<br><br>
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <form action="{{ route('ruangan.update', $ruangan->id) }}" method="POST" class="forms-sample" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                  <div class="form-group row">
                    <label for="exampleInputUsername2" class="col-sm-3 col-form-label">Nama Ruangan</label>
                    <div class="col-sm-9">
                      <input type="text" name="nama" class="form-control" id="exampleInputUsername2" value="{{ $ruangan->nama }}">
                    </div>
                  </div>
                  <div class="form-group row">
                    <label for="exampleSelectGender"  class="col-sm-3 col-form-label">Kategori Ruangan</label>
                    <div class="col-sm-9">
                        <select class="form-control" id="exampleSelectGender" name="kategori_ruangan_id">
                            <option>-- Pilih Kategori Ruangan --</option>
                            @foreach ($kategori_ruangan as $kat)
                            <option value="{{ $kat->id }}" {{ ($kat->id == $ruangan->kategori_ruangan_id) ? 'selected' : '' }}>{{ $kat->nama }}</option>
                            @endforeach
                        </select>
                    </div>
                    </div>
                    <div class="form-group row">
                        <label for="exampleSelectGender"  class="col-sm-3 col-form-label">Gedung</label>
                        <div class="col-sm-9">
                            <select class="form-control" id="exampleSelectGender" name="gedung_id">
                                <option>-- Pilih Kategori Gedung --</option>
                                @foreach ($gedung as $gd)
                                <option value="{{ $gd->id }}"  {{ ($gd->id == $ruangan->gedung_id) ? 'selected' : '' }}>{{ $gd->nama }}</option>
                                @endforeach
                            </select>
                        </div>
                        </div>
                  <div class="form-group row">
                    <label for="exampleInputMobile" class="col-sm-3 col-form-label">Lantai</label>
                    <div class="col-sm-9">
                        <input type="text" name="lantai" class="form-control" value="{{ $ruangan->lantai }}">
                    </div>
                  </div>
                  <div class="form-group row">
                    <label for="exampleInputMobile" class="col-sm-3 col-form-label">Kapasitas</label>
                    <div class="col-sm-9">
                        <input type="text" name="kapasitas" class="form-control" value="{{ $ruangan->kapasitas }}">
                    </div>
                  </div>
                  <div class="form-group row">
                    <label for="exampleInputMobile" class="col-sm-3 col-form-label">Foto 1</label>
                    <div class="col-sm-9">
                        <input type="file" name="foto1" class="form-control" >
                    </div>
                  </div>
                  <div class="form-check form-check-flat form-check-primary">
                  </div>
                  <button type="submit" name="proses" class="btn btn-primary mr-2">Ubah</button>
                  <a href="{{ url('ruangan')}}" class="btn btn-warning text-white">Batal</a>
                </form>
              </div>
            </div>
          </div>
    </div>
    </div>
@endsection

resources/views/ruangan/index.blade.php
@extends('admin.index')

@section('content')
@if(Auth::user()->role != 'peminjam')
<div class="content-wrapper">

    <div class="d-flex justify-content-between my-3">
        <h3>Data Ruangan</h3>
        <div>
            <a class="btn btn-info btn-sm btn-icon-text mr-3" href="{{ route('ruangan.create')}}">
                Tambah
                <i class="typcn typcn-plus btn-icon-append"></i>
              </a>
              <a href="{{ url('/generate-pdf') }}"  class="btn btn-success btn-sm btn-icon-text mr-3" title="Edit data ruangan">
                PDF
                <i class="typcn typcn-folder  btn-icon-append"></i>
              </a>
              <a href="{{ url('/ruangan-pdf') }}"  class="btn btn-success btn-sm btn-icon-text mr-3" title="Edit data ruangan">
                Donwload
                <i class="typcn typcn-download btn-icon-append"></i>
              </a>
              <a href="{{ url('/ruangan-pdf') }}"  class="btn btn-success btn-sm btn-icon-text mr-3" title="Edit data ruangan">
                Excel
                <i class="typcn typcn-download  btn-icon-append"></i>
              </a>
        </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="table-responsive pt-3">
            <table class="table table-striped project-orders-table">
              <thead>
                <tr>
                  <th class="ml-5">No</th>
                  <th>Nama Ruangan</th>
                  <th>Kategori Ruangan</th>
                  <th>Gedung</th>
                  <th>Kapasitas</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                  @foreach ($ruangan as $r)

                <tr>
                  <td>{{ ++$i }}</td>
                  <td>{{ $r->nama }}</td>
                  <td>{{ $r->kategoriRuangan->nama }} </td>
                  <td>{{ $r->gedung->nama }} </td>
                  <td>{{ $r->kapasitas }}</td>
                  <td>
                    <div class="d-flex align-items-center">
                      <a href="{{ route('ruangan.show', $r->id) }}" title="Show data ruangan"  class="btn btn-info btn-sm btn-icon-text mr-3">
                        View
                        <i class="typcn typcn-eye btn-icon-append"></i>
                      </a>
                        <a href="{{ route('ruangan.edit', $r->id) }}"  class="btn btn-success btn-sm btn-icon-text mr-3" title="Edit data ruangan">
                        Edit
                        <i class="typcn typcn-edit btn-icon-append"></i>
                      </a>
                      {{-- <form action="{{ route('ruangan.destroy', $r->id)}}" method="POST">
                        @csrf
                        @method('DELETE') --}}
                        <a type="submit" class="btn btn-danger btn-sm btn-icon-text button delete-confirm" title="Hapus data" href="/ruangan-delete/{{$r->id}}">
                            Delete
                            <i class="typcn typcn-delete-outline btn-icon-append"></i>
                          </a>

                      {{-- </form> --}}
                    </div>
                  </td>
                </tr>
                @endforeach
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
  @else
  @include('access')
  @endif
@endsection

resources/views/ruangan/mypdf.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Hi</title>
</head>
<body>
    <h1>{{ $title }}</h1>
    <p>{{ $date }}</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
    consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
    proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</body>
</html>

resources/views/ruangan/ruangan-list.blade.php
@extends('landingpage.index')

@section('content')
    <!-- Our Room Area Start -->
    <section class="roberto-rooms-area">
        <div class="rooms-slides owl-carousel">
            <!-- Looping data Gedung -->
            @foreach ($gedungs as $gd)
            <div class="single-room-slide d-flex align-items-center">
                <!-- Thumbnail -->
                <div class="room-thumbnail h-100 bg-img" style="background-image: url({{ asset('img/gedung/'.$gd->foto)}});"></div>

                <!-- Content -->
                <div class="room-content">
                    <h2 data-animation="fadeInUp" data-delay="100ms">{{ $gd->nama }}</h2>
                    <ul class="room-feature" data-animation="fadeInUp" data-delay="500ms">
                        <li><span><i class="fa fa-check"></i> Kode</span> <span>: {{ $gd->kode }}</span></li>
                        <li><span><i class="fa fa-check"></i> Alamat</span> <span>: {{ $gd->alamat }}</span></li>
                    </ul>
                    <a href="#" class="btn roberto-btn mt-30" data-animation="fadeInUp" data-delay="700ms">View Details</a>
                </div>
            </div>
            @endforeach
        </div>
    </section>
    <!-- Our Room Area End -->
@endsection

resources/views/ruangan/ruanganpdf.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Data Ruangan</title>
</head>
<body>
    <h3 align="center">Data Ruangan</h3>
    <table align="center" border="1" cellpadding="10" cellspacing="0">
        <thead>
          <tr>
            <th>No</th>
            <th>Nama Ruangan</th>
            <th>Kategori Ruangan</th>
            <th>Gedung</th>
            <th>Kapasitas</th>
          </tr>
        </thead>
        <tbody>
            @foreach ($data as $dt)
            @php
                $i = 0
            @endphp
          <tr>
            <td>{{ ++$i }}</td>
            <td>{{ $dt->nama }}</td>
            <td>{{ $dt->kategoriRuangan->nama }} </td>
            <td>{{ $dt->gedung->nama }} </td>
            <td>{{ $dt->kapasitas }}</td>
          </tr>
          @endforeach
        </tbody>
      </table>

</body>
</html>