routes/web.php
<?php

use App\Http\Controllers\ApiConsumerController;
use App\Http\Controllers\GedungController;
use App\Http\Controllers\KategoriRuanganController;
use App\Http\Controllers\FasilitasController;
use App\Http\Controllers\RuanganController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// =========== Route For Landing-page ===========
Route::view('/', 'landingpage.home');
Route::view('/home', 'landingpage.home');
Route::view('/about', 'landingpage.about');
Route::view('/services', 'landingpage.services');
Route::view('/blog', 'landingpage.blog');
Route::view('/contact', 'landingpage.contact');
Route::view('/list', 'landingpage.list');
Route::view('/aula-atas', 'landingpage.aula-atas');
Route::view('/aula-bawah', 'landingpage.aula-bawah');
Route::view('/lapangan', 'landingpage.lapangan');
Route::view('/tepas', 'landingpage.tepas');

// =========== Route For Admin ===========
Route::view('/admin', 'admin.home');
// Route::view('/peminjaman', 'admin.peminjaman');
Route::view('/admin/pages/basictable', 'admin.pages.basictable');
Route::view('/admin/pages/basicelement', 'admin.pages.basicelement');
Route::view('/admin/pages/chart', 'admin.pages.chart');
Route::view('/admin/pages/icons', 'admin.pages.icons');

// =========== Route For Bisnis Proses ===========
// Route::resource('/gedung', GedungController::class)->middleware('auth');
// Route::resource('/users', UserController::class)->middleware('auth');
// Route::resource('/fasilitas', FasilitasController::class)->middleware('auth');
// Route::resource('/ruangan', RuanganController::class)->middleware('auth');
// // Route::get('/ruangan-delete/{id}', 'RuanganController@destroy')->name('ruangans.destory');
// // Route::get('/ruangan-delete/{id}', [RuanganController::class, 'destory'] )->name('destory');
// Route::get('/ruangan-delete/{id}', 'App\Http\Controllers\RuanganController@destroy')->middleware('auth');
// Route::resource('/kategori-ruangan', KategoriRuanganController::class);
// Route::get('/gedung-list', [GedungController::class, 'gedungList']);


// // =========== Route For Export PDF ===========
// Route::get('/generate-pdf', [RuanganController::class, 'generatePDF'])->middleware('auth');
// Route::get('/ruangan-pdf', [RuanganController::class, 'ruanganPDF'])->middleware('auth');


// Route Group for every auth
Route::group(['middleware' => ['access']], function (){
Route::resource('/gedung', GedungController::class);
Route::resource('/users', UserController::class);
Route::resource('/fasilitas', FasilitasController::class);
Route::resource('/ruangan', RuanganController::class);
// Route::get('/ruangan-delete/{id}', 'RuanganController@destroy')->name('ruangans.destory');
// Route::get('/ruangan-delete/{id}', [RuanganController::class, 'destory'] )->name('destory');
Route::get('/ruangan-delete/{id}', 'App\Http\Controllers\RuanganController@destroy');
Route::resource('/kategori-ruangan', KategoriRuanganController::class);
Route::get('/gedung-list', [GedungController::class, 'gedungList']);

// =========== Route For Export PDF ===========
Route::get('/generate-pdf', [RuanganController::class, 'generatePDF']);
Route::get('/ruangan-pdf', [RuanganController::class, 'ruanganPDF']);

// api get for ruangan
// Route::get('api/{service}', [ApiConsumerController::class,'list']);
// Route::get('api/{service}/{id}', [ApiConsumerController::class,'detail']);

});
Route::get('/peminjaman', function() {
    return view('admin.peminjaman');
});



// Route cara 2
// Route::middleware(['admin', 'staff'])->group(function () {
//     Route::resource('/gedung', GedungController::class);
//     Route::resource('/users', UserController::class);
//     Route::resource('/fasilitas', FasilitasController::class);
//     Route::resource('/ruangan', RuanganController::class);
//     // Route::get('/ruangan-delete/{id}', 'RuanganController@destroy')->name('ruangans.destory');
//     // Route::get('/ruangan-delete/{id}', [RuanganController::class, 'destory'] )->name('destory');
//     Route::get('/ruangan-delete/{id}', 'App\Http\Controllers\RuanganController@destroy');
//     Route::resource('/kategori-ruangan', KategoriRuanganController::class);
//     Route::get('/gedung-list', [GedungController::class, 'gedungList']);


//     // =========== Route For Export PDF ===========
//     Route::get('/generate-pdf', [RuanganController::class, 'generatePDF']);
//     Route::get('/ruangan-pdf', [RuanganController::class, 'ruanganPDF']);
//     // Route::view('/peminjaman', 'admin.peminjaman');

// });
// for authentication user
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::view('/after-register', 'landingpage.after_register');
Route::view('/access-denied', 'access');

app/Models/Gedung.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Gedung extends Model
{
    use HasFactory;

    protected $table = 'gedung';

    protected $fillable =[
        'kode', 'nama', 'alamat', 'foto'
    ];

    // database relation one to many
    public function ruangan()
    {
        return $this->hasMany(Ruangan::class);
    }
}

app/Http/Controllers/GedungController.php
<?php

namespace App\Http\Controllers;

// use App\Helpers\ApiFormater;
use Illuminate\Http\Request;
use App\Models\Gedung;

class GedungController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    // tampil data for admin page

    public function index()
    {
        // Tampil Data from Database
        $gedungs = Gedung::all();
        return view('gedung.index',compact('gedungs'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
        // if($gedungs){
        //     return ApiFormater::createApi(200, 'success', $gedungs);
        // }else{
        //     return ApiFormater::createApi(400, 'failed');
        // }

    }

    // public function index()
    // {
    //     // Tampil Data from Database
    //     $gedungs = Gedung::latest()->paginate(5);

    //     return view('gedung.index',compact('gedungs'))
    //         ->with('i', (request()->input('page', 1) - 1) * 5);
    // }

    // tampil data for landingpage
    public function gedungList()
    {
        // Tampil Data from Database
        $gedungs = Gedung::latest()->paginate(5);

        return view('gedung.gedung-list',compact('gedungs'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // Tambah ke form input data
        return view('gedung.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        // try {
        // Proses input data gedung with foto
        $request->validate([
            'kode' => 'required|unique:gedung,kode|max:6',
            'nama' => 'required|max:225',
            'alamat' => 'required',
            'foto' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
        ]);

        $input = $request->all();

        // logic for proses foto
        if ($image = $request->file('foto')) {
            $destinationPath = 'img/gedung';
            $profileImage = date('YmdHis') . "." . $image->getClientOriginalExtension();
            $image->move($destinationPath, $profileImage);
            $input['foto'] = "$profileImage";
        }

        // input create gedung function
        $gedungs = Gedung::create($input);
        $data = Gedung::where('id', '=', $gedungs->id)->get();


        // if($data){
        //     return ApiFormater::createApi(200, 'success create data', $data);
        // }else{
        //     return ApiFormater::createApi(400, 'failed');
        // }

        // } catch (\Exception $error) {
        //     return ApiFormater::createApi(400, 'failed');
        // }

        // kembali ke page
        return redirect()->route('gedung.index')
                        ->with('success','Gedung created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // //
        // $data = Gedung::where('id', '=', $id)->get();


        // if($data){
        //     return ApiFormater::createApi(200, 'show data', $data);
        // }else{
        //     return ApiFormater::createApi(400, 'show data failed');
        // }

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //

        // try {
        //     // Proses input data gedung with foto
        //     $request->validate([
        //         'kode' => 'required|unique:gedung,kode|max:6',
        //         'nama' => 'required|max:225',
        //         'alamat' => 'required',
        //         'foto' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
        //     ]);

        //     $gedungs = Gedung::findOrFail($id);
        //     // input create gedung function
        //     $gedungs->update($request->all());
        //     $data = Gedung::where('id', '=', $id)->get();


        //     if($data){
        //         return ApiFormater::createApi(200, 'success update data', $data);
        //     }else{
        //         return ApiFormater::createApi(400, 'failed');
        //     }

        //     } catch (\Exception $error) {
        //         return ApiFormater::createApi(400, 'failed');
        //     }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        // $gedungs = Gedung::findOrFail($id);
        // $data = $gedungs->delete();

        // if($data){
        //     return ApiFormater::createApi(200, 'success Destroy data', $data);
        // }else{
        //     return ApiFormater::createApi(400, 'failed');
        // }

    }
}

resources/views/gedung/create.blade.php
@extends('admin.index')

@section('content')
    <div class="content-wrapper">
    <div class="row">
        <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
              <div class="card-body">
                <h4 class="card-title">Form input Gedung</h4>
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <strong>Whoops!</strong> There were some problems with your input.<br><br>
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <form action="{{ route('gedung.store') }}" method="POST" class="forms-sample" enctype="multipart/form-data">
                    @csrf
                  <div class="form-group row">
                    <label for="exampleInputUsername2" class="col-sm-3 col-form-label">Kode</label>
                    <div class="col-sm-9">
                      <input type="text" name="kode" class="form-control" id="exampleInputUsername2" placeholder="Kode">
                    </div>
                  </div>
                  <div class="form-group row">
                    <label for="exampleInputEmail2" class="col-sm-3 col-form-label">Nama Gedung</label>
                    <div class="col-sm-9">
                      <input type="text" name="nama" class="form-control" id="exampleInputEmail2" placeholder="Nama Gedung">
                    </div>
                  </div>
                  <div class="form-group row">
                    <label for="exampleInputMobile" class="col-sm-3 col-form-label">Alamat</label>
                    <div class="col-sm-9">
                      <textarea type="text" name="alamat" class="form-control" id="exampleInputMobile" placeholder="Alamat"></textarea>
                    </div>
                  </div>
                  <div class="form-group row">
                    <label for="exampleInputMobile" class="col-sm-3 col-form-label">Foto</label>
                    <div class="col-sm-9">
                        <input type="file" name="foto" class="form-control" placeholder="foto">
                    </div>
                  </div>
                  <div class="form-check form-check-flat form-check-primary">
                  </div>
                  <button type="submit" name="proses" class="btn btn-primary mr-2">Submit</button>
                  <a href="{{ url('gedung')}}" class="btn btn-warning text-white">Batal</a>
                </form>
              </div>
            </div>
          </div>
    </div>
    </div>
@endsection

resources/views/gedung/gedung-list.blade.php
@extends('landingpage.index')

@section('content')
    <!-- Our Room Area Start -->
    <section class="roberto-rooms-area">
        <div class="rooms-slides owl-carousel">
            <!-- Looping data Gedung -->
            @foreach ($gedungs as $gd)
            <div class="single-room-slide d-flex align-items-center">
                <!-- Thumbnail -->
                <div class="room-thumbnail h-100 bg-img" style="background-image: url({{ asset('img/gedung/'.$gd->foto)}});"></div>

                <!-- Content -->
                <div class="room-content">
                    <h2 data-animation="fadeInUp" data-delay="100ms">{{ $gd->nama }}</h2>
                    <ul class="room-feature" data-animation="fadeInUp" data-delay="500ms">
                        <li><span><i class="fa fa-check"></i> Kode</span> <span>: {{ $gd->kode }}</span></li>
                        <li><span><i class="fa fa-check"></i> Alamat</span> <span>: {{ $gd->alamat }}</span></li>
                    </ul>
                    <a href="#" class="btn roberto-btn mt-30" data-animation="fadeInUp" data-delay="700ms">View Details</a>
                </div>
            </div>
            @endforeach
        </div>
    </section>
    <!-- Our Room Area End -->
@endsection

resources/views/gedung/index.blade.php
@extends('admin.index')

@section('content')
<div class="content-wrapper">

    <div class="d-flex justify-content-between my-3">
        <h3>Data Gedung</h3>
        <a class="btn btn-info btn-sm btn-icon-text mr-3" href="{{ route('gedung.create')}}">
            Tambah
            <i class="typcn typcn-plus btn-icon-append"></i>
          </a>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="table-responsive pt-3">
            <table class="table table-striped project-orders-table">
              <thead>
                <tr>
                  <th class="ml-5">No</th>
                  <th>Kode Gedung</th>
                  <th>Nama Gedung</th>
                  <th>Alamat</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                  @foreach ($gedungs as $gd)

                <tr>
                  <td>{{ ++$i }}</td>
                  <td>{{ $gd->kode }}</td>
                  <td>{{ $gd->nama }} </td>
                  <td>{{ $gd->alamat }}</td>
                  <td>
                    <div class="d-flex align-items-center">
                      <button type="button" class="btn btn-success btn-sm btn-icon-text mr-3">
                        Edit
                        <i class="typcn typcn-edit btn-icon-append"></i>
                      </button>
                      <button type="button" class="btn btn-danger btn-sm btn-icon-text">
                        Delete
                        <i class="typcn typcn-delete-outline btn-icon-append"></i>
                      </button>
                    </div>
                  </td>
                </tr>
                @endforeach
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

  </div>

@endsection